trigger: none

variables:
  - name: variable1
  - name: variable2


jobs:
- job: Build
  pool:
    name: Default
  steps:
  - script: |
      echo "Variable 1: $(variable1)"
      echo "Variable 2: $(variable2)"
      # Sample REST API call to retrieve VM name and service name
      #curl "https://your-api-endpoint" | jq '.vmName, .serviceName' > output.json
      # Further steps to parse output.json can be added here
    displayName: 'Run Script and Fetch Data'
  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: output
      targetPath: $(System.DefaultWorkingDirectory)/output.json
    displayName: 'Publish Output Artifact'
