trigger:
- main  # Replace with your branch if different

pool:
  vmImage: 'windows-latest'

variables:
  environmentName: ${{ parameters.environmentName }}
  serviceName: ${{ parameters.serviceName }}

jobs:
- deployment: DeployToVM
  displayName: 'Deploy to Virtual Machine'
  environment: 'MyVMEnvironment'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: PowerShell@2
          displayName: 'Restart NAV Server Instance'
          inputs:
            targetType: 'inline'
            script: |
              param(
                [string]$serviceName
              )
              Restart-Service -Name $serviceName
          env:
            serviceName: $(serviceName)
