trigger: none

variables:
  - name: Server_name
  - name: Service_name

jobs:
- job: Build
  pool:
    name: Pipeline
  steps:
  - script: |
      echo "Variable 1: $(Server_name)"
      echo "Variable 2: $(Service_name)"
    displayName: 'Run Script and Fetch Data'
  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: output
      targetPath: $(System.DefaultWorkingDirectory)/output.json
    displayName: 'Publish Output Artifact'
